### ISSUE TITLE
Sample data is not fully provided

### ISSUE THREAD

**Issue by iwatobipen** [insilicomedicine/BiAAE#2]
Dear,
I would like to test the code with l1000 data set.
But when I got data from the link url where you provided in README, I could't find the file below in the zip archive.
'robust_normalized_tumors.npz'
Could you please add the file to the zip archive?

Thanks.

**Comment by danpol** [comment]
Hi, @iwatobipen!
Did you download the training data from step 4 of [Installation instructions](https://github.com/insilicomedicine/BiAAE#installation)?

**Comment by iwatobipen** [comment]
Sorry, I tried downloading again but didn't work well.
Thanks,

**Comment by danpol** [comment]
Did you use this link? https://drive.google.com/drive/folders/1rMQmnAVMPPQxQTw0pjVvrGE-Toxys-w7

**Comment by iwatobipen** [comment]
Yes I used the link and downloaed lincs as a zip archive. But the file contains two files.
1,experiments_filtered.csv
2,robust_normalized_controls.npz

**Comment by danpol** [comment]
@iwatobipen, this file is there, on Google drive (see screenshot). Just in case you have a problem with downloading it, try using this [link](https://drive.google.com/file/d/1XIn0QkaDqg6Ol5vIO7URIAAWX_7xghH1/view?usp=sharing)
![image](https://user-images.githubusercontent.com/1181277/96598699-cec26300-12f7-11eb-90bf-e765254b9a21.png)
